export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const FETCH_PATIENTS_WORLD = 'FETCH_PATIENTS_WORLD';
export const UPDATE_PATIENTS_WORLD = 'UPDATE_PATIENTS_WORLD';

export const FETCH_DECLARERS = 'FETCH_DECLARERS';
export const ADD_DECLARER = 'ADD_DECLARER';
export const UPDATE_DECLARER = 'UPDATE_DECLARER';
export const DELETE_DECLARER = 'DELETE_DECLARER';

export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';